# Generated by Django 4.2.1 on 2023-06-09 08:54

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredientamount_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Цветовой HEX-код', max_length=7, unique=True, validators=[recipes.validators.ColorValidator], verbose_name='HEX-код цвета'),
        ),
    ]
